language: node_js
sudo: 'false'
before_script:
  - npm install -g polymer-cli
  - git checkout package-lock.json
  - >-
    npm run format && git diff --exit-code || (echo -e '\n\033[31mERROR:\033[0m
    Project is not formatted. Please run "npm run format".' && false)
env:
  global:
    - secure: LvRH7RiBsVoWm4dBcxnWOuJ1gcDG5iLB9WBOwmcq65KNlADFMqK72PibpaslTtESFjK6luQnPH/9o7sWTCD3gsRdOOsUwRzlc+0wQu/dmtg7X/TWGORlWLTa6Fgso7Zz0i74unZfNi5ipowjTB+VomXf4/fyPM9kUSxdLWtNxGY=
    - secure: DN5ZVv5gFl+HY6qWquZrN3Yc4pGnPWPGTK+DPvY0YBI9DsSNx0jZcoHxILWw6sJjaEhwfAl+IiW87Icfj7qMTNHAZlfx+uXkBJ39BxQezXXO8IPo7MiDektZCOZX7rENtzdQFbm9qptn7PC24i28KVkgrbLlzjDGN+QB5pVR6tg=
node_js: 'node'
addons:
  firefox: latest
  chrome: stable
script:
  - xvfb-run polymer test --module-resolution=node --npm
  - 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test --module-resolution=node --npm -s ''default''; fi'
dist: trusty
cache:
  directories:
    - node_modules

